import { createFileRoute } from "@tanstack/react-router";
import { Activity, ArrowRight, Bot, CircleAlert, Clock3, Database, ExternalLink, Gauge, RefreshCw, Send, ShieldCheck, Wifi } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/bot")({ component: BotConsole });

const events = [
  { type: "application_submitted", target: "#tryouts", time: "2 min ago", state: "Delivered" },
  { type: "profile_updated", target: "#roster", time: "18 min ago", state: "Delivered" },
  { type: "tournament_created", target: "#announcements", time: "42 min ago", state: "Delivered" },
  { type: "system_error", target: "#bot-logs", time: "1 hr ago", state: "Retrying" },
];

function BotConsole() {
  const [notice, setNotice] = useState("");
  const [refreshing, setRefreshing] = useState(false);
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const refresh = () => { setRefreshing(true); window.setTimeout(() => { setRefreshing(false); showNotice("Bot status refreshed."); }, 700); };
  return <main className="mx-auto w-full max-w-6xl px-4 py-12 sm:px-6 sm:py-20">
    <div className="flex flex-wrap items-start justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-accent">VANT / BOT CONTROL</p><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-0.06em]">VANTBOT <span className="text-accent">/</span> Console</h1><p className="mt-4 max-w-2xl text-muted">A Node web control plane for the Discord worker. Monitor delivery, verify sync, and keep the operational layer visible.</p></div><div className="flex gap-2"><button className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-line bg-surface px-4 text-[11px] uppercase tracking-[0.12em]" onClick={refresh}><RefreshCw className={refreshing ? "h-4 w-4 animate-spin" : "h-4 w-4"} /> Refresh</button><button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-accent px-4 text-[11px] uppercase tracking-[0.12em] text-white" onClick={() => showNotice("Worker restart queued. Connect the worker host to execute it.")}><Activity className="h-4 w-4" /> Restart worker</button></div></div>
    <section className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "Bot gateway", value: "Online", detail: "Connected 14m", icon: Wifi, tone: "text-ok" }, { label: "Web sync", value: "Healthy", detail: "Signed requests", icon: ShieldCheck, tone: "text-ok" }, { label: "Event queue", value: "04", detail: "01 retrying", icon: Send, tone: "text-warn" }, { label: "Last heartbeat", value: "12 sec", detail: "Worker interval", icon: Clock3, tone: "text-accent" }].map((stat) => <div className="glass-card rounded-2xl p-5" key={stat.label}><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.14em] text-subtle">{stat.label}</span><stat.icon className={`h-4 w-4 ${stat.tone}`} /></div><p className="mt-4 font-display text-2xl font-semibold">{stat.value}</p><p className="mt-1 text-xs text-muted">{stat.detail}</p></div>)}</section>
    <section className="mt-4 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="glass-card rounded-2xl p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-2xl font-semibold">Event delivery</h2><p className="mt-1 text-sm text-muted">Signed web ↔ Discord events from the VANT outbox.</p></div><button className="text-xs text-accent underline" onClick={() => showNotice("Event log export queued.")}>Export log</button></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="font-mono text-[10px] uppercase tracking-[0.12em] text-subtle"><tr><th className="pb-3">Event</th><th className="pb-3">Channel</th><th className="pb-3">When</th><th className="pb-3">State</th></tr></thead><tbody>{events.map((event) => <tr className="border-t border-line" key={`${event.type}-${event.time}`}><td className="py-4 font-mono text-xs">{event.type}</td><td className="py-4 text-muted">{event.target}</td><td className="py-4 text-muted">{event.time}</td><td className={event.state === "Retrying" ? "py-4 text-warn" : "py-4 text-ok"}>{event.state}</td></tr>)}</tbody></table></div></div><div className="glass-card rounded-2xl p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent-dim text-accent"><Bot className="h-5 w-5" /></span><div><h2 className="font-display text-xl font-semibold">Worker runtime</h2><p className="text-xs text-muted">Python Discord process</p></div></div><div className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><span className="text-muted">Host</span><span>Persistent worker</span></div><div className="flex justify-between"><span className="text-muted">Region</span><span>us-east-1</span></div><div className="flex justify-between"><span className="text-muted">Version</span><span className="font-mono text-xs">v0.8.4</span></div><div className="flex justify-between"><span className="text-muted">Last deploy</span><span className="font-mono text-xs">52a87ce</span></div></div><button className="mt-7 flex w-full items-center justify-between border-t border-line pt-4 text-xs text-accent" onClick={() => showNotice("Worker logs are available on the persistent host.")}>View worker logs <ArrowRight className="h-4 w-4" /></button></div></section>
    <section className="mt-4 grid gap-4 md:grid-cols-3"><div className="glass-card rounded-2xl p-6"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-accent" /><h3 className="font-display text-lg font-semibold">Supabase sync</h3></div><p className="mt-3 text-sm leading-6 text-muted">The worker reads pending events and ACKs them only after Discord delivery succeeds.</p><button className="mt-5 inline-flex items-center gap-2 text-xs text-accent" onClick={() => showNotice("Sync contract opened.")}>Open sync contract <ExternalLink className="h-3.5 w-3.5" /></button></div><div className="glass-card rounded-2xl p-6"><div className="flex items-center gap-2"><Gauge className="h-4 w-4 text-accent" /><h3 className="font-display text-lg font-semibold">Health endpoint</h3></div><p className="mt-3 text-sm leading-6 text-muted">Use the Node endpoint to monitor configuration without exposing any secret values.</p><code className="mt-5 block rounded-lg bg-bg p-3 font-mono text-xs text-muted">GET /api/bot/health</code></div><div className="glass-card rounded-2xl p-6"><div className="flex items-center gap-2"><CircleAlert className="h-4 w-4 text-warn" /><h3 className="font-display text-lg font-semibold">Deployment note</h3></div><p className="mt-3 text-sm leading-6 text-muted">Vercel currently blocks deployments because the project billing address is incomplete. Update it in Vercel before redeploying this web console.</p><button className="mt-5 inline-flex items-center gap-2 text-xs text-accent" onClick={() => showNotice("Open Vercel billing settings to unblock deployments.")}>Open checklist <ArrowRight className="h-3.5 w-3.5" /></button></div></section>
    {notice && <div className="fixed bottom-6 right-6 z-20 rounded-xl border border-line bg-surface px-4 py-3 text-sm text-fg shadow-2xl">{notice}</div>}
  </main>;
}
