import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, ChevronDown, ChevronRight, Crosshair, Gamepad2, Menu, Search, Shield, Swords, Trophy, Users, X, Zap } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/")({ component: ValorantDemo });

const events = [
  { title: "VANT OPEN // SPLIT 01", tag: "OPEN QUALIFIER", date: "JUN 28 — 30", teams: "128 / 128", prize: "$2,500", status: "FULL", tone: "red" },
  { title: "NIGHT SHIFT CUP", tag: "WEEKLY SERIES", date: "JUL 04 · 20:00", teams: "24 / 32", prize: "$750", status: "8 SLOTS", tone: "purple" },
  { title: "VANT INVITATIONAL", tag: "PRO CIRCUIT", date: "JUL 19 — 21", teams: "16 TEAMS", prize: "$10,000", status: "INVITE ONLY", tone: "gold" },
];

const leaderboard = [
  ["01", "M80", "1,842", "↑ 2"], ["02", "G2 Esports", "1,790", "—"], ["03", "SEN City", "1,744", "↑ 4"], ["04", "NRG Academy", "1,698", "↓ 1"], ["05", "Cloud9 White", "1,655", "↑ 1"],
];

function ValorantDemo() {
  const [tab, setTab] = useState("home");
  const [menu, setMenu] = useState(false);
  const [modal, setModal] = useState("");
  return <main className="realm-demo">
    <header className="realm-header"><button className="realm-logo" onClick={() => setTab("home")}><span className="realm-logo-mark"><i /><i /><i /></span><span>VANT<b>REALM</b></span></button><nav>{[["home", "HOME"], ["tournaments", "TOURNAMENTS"], ["ranked", "RANKED"], ["players", "PLAYERS"]].map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</nav><div className="realm-head-actions"><button className="realm-search" onClick={() => setModal("search")}><Search size={15} /> SEARCH</button><button className="realm-login" onClick={() => setModal("login")}>SIGN IN</button><button className="realm-menu" onClick={() => setMenu(!menu)}><Menu size={18} /></button></div></header>
    {menu && <div className="realm-mobile-nav">{[["home", "HOME"], ["tournaments", "TOURNAMENTS"], ["ranked", "RANKED"], ["players", "PLAYERS"]].map(([id, label]) => <button key={id} onClick={() => { setTab(id); setMenu(false); }}>{label}<ChevronRight size={15} /></button>)}</div>}
    {tab === "home" && <Home setTab={setTab} setModal={setModal} />}
    {tab === "tournaments" && <Tournaments setModal={setModal} />}
    {tab === "ranked" && <Ranked />}
    {tab === "players" && <Players />}
    <footer className="realm-footer"><div><button className="realm-logo"><span className="realm-logo-mark"><i /><i /><i /></span><span>VANT<b>REALM</b></span></button><p>The competitive layer for VALORANT players.<br />Built for the next round.</p></div><div><span>PLATFORM</span><a onClick={() => setTab("tournaments")}>Tournaments</a><a onClick={() => setTab("ranked")}>Ranked ladder</a><a onClick={() => setTab("players")}>Players</a></div><div><span>COMMUNITY</span><a>Discord</a><a>Twitter / X</a><a>Support</a></div><small>© 2026 VANT REALM · NOT AFFILIATED WITH RIOT GAMES</small></footer>
    {modal && <Modal type={modal} close={() => setModal("")} />}
  </main>;
}

function Home({ setTab, setModal }: { setTab: (tab: string) => void; setModal: (modal: string) => void }) { return <>
  <section className="realm-hero"><div className="hero-noise" /><div className="hero-copy"><span className="eyebrow red">VANT REALM / SEASON 01</span><h1>THE NEXT<br /><em>ROUND</em><br />IS YOURS.</h1><p>Compete in community tournaments, climb the ranked ladder, and find your five.</p><div className="hero-actions"><button className="realm-btn red-btn" onClick={() => setTab("tournaments")}>ENTER THE CIRCUIT <ArrowRight size={15} /></button><button className="text-btn" onClick={() => setModal("how")}>HOW IT WORKS <ChevronRight size={15} /></button></div></div><div className="hero-mark"><div className="hero-cross"><span>V</span></div><div className="hero-stat"><b>05</b><span>ROUNDS TO<br />THE TOP</span></div></div><div className="hero-bottom"><span><i className="live-dot" /> LIVE CIRCUIT</span><span>NA / EU / LATAM</span><span>UPDATED 04.26.26</span></div></section>
  <section className="realm-section circuit-section"><div className="section-head"><div><span className="eyebrow">01 / THE CIRCUIT</span><h2>PLAY THE <em>FIELD.</em></h2></div><button className="outline-btn" onClick={() => setTab("tournaments")}>VIEW ALL EVENTS <ArrowRight size={14} /></button></div><div className="event-grid">{events.map((event) => <button key={event.title} className={`event-card ${event.tone}`} onClick={() => setModal(event.status === "FULL" ? "full" : "register")}><div className="event-art"><span className="event-glyph">{event.tone === "gold" ? "✦" : event.tone === "purple" ? "◈" : "×"}</span><span className="event-region">VANT / {event.tone === "gold" ? "PRO" : "OPEN"}</span></div><div className="event-info"><span className="event-tag">{event.tag}</span><h3>{event.title}</h3><div className="event-meta"><span><CalendarDays size={13} /> {event.date}</span><span><Users size={13} /> {event.teams}</span></div><div className="event-bottom"><strong>{event.prize}</strong><span className={`event-status ${event.status === "FULL" ? "full" : ""}`}>{event.status} <ArrowRight size={13} /></span></div></div></button>)}</div></section>
  <section className="realm-section split-section"><div className="next-match"><div className="section-head compact"><div><span className="eyebrow">02 / UP NEXT</span><h2>THE <em>SHOWDOWN.</em></h2></div><span className="match-live"><i className="live-dot" /> LIVE IN 02:14:08</span></div><div className="match-card"><div className="match-top"><span>VANT OPEN / UPPER FINAL</span><span>BO3 · PATCH 10.07</span></div><div className="match-teams"><div><span className="team-badge red-badge">M8</span><b>M80</b><small>NA #01</small></div><strong>VS</strong><div><span className="team-badge blue-badge">G2</span><b>G2 ESPORTS</b><small>NA #02</small></div></div><div className="match-footer"><span>MAP VETO IN PROGRESS</span><button onClick={() => setModal("match")}>MATCH CENTER <ArrowRight size={13} /></button></div></div></div><div className="ladder"><div className="section-head compact"><div><span className="eyebrow">03 / LEADERBOARD</span><h2>THE <em>LADDER.</em></h2></div><button className="tiny-btn" onClick={() => setTab("ranked")}>FULL RANKING <ArrowRight size={13} /></button></div><div className="ladder-card">{leaderboard.map((row) => <div className="rank-row" key={row[0]}><span className="rank-num">{row[0]}</span><span className="rank-team"><span className="mini-shield" />{row[1]}</span><b>{row[2]}</b><span className={row[3].startsWith("↓") ? "down" : "up"}>{row[3]}</span></div>)}</div></div></section>
  <section className="realm-cta"><span className="eyebrow red">NO SPECTATORS</span><h2>BUILD YOUR<br /><em>LEGACY.</em></h2><button className="realm-btn white-btn" onClick={() => setModal("register")}>CREATE A TEAM <ArrowRight size={15} /></button></section>
</>; }

function Tournaments({ setModal }: { setModal: (modal: string) => void }) { return <section className="page-section"><div className="page-heading"><span className="eyebrow red">VANT REALM / EVENTS</span><h1>TOURNAMENTS<br /><em>ARE LIVE.</em></h1><p>Find your next bracket. Every skill level, every weekend.</p></div><div className="filter-bar"><button className="filter-active">ALL EVENTS</button><button>OPEN</button><button>WEEKLY</button><button>PRO CIRCUIT</button><span /><button>ALL REGIONS <ChevronDown size={14} /></button></div><div className="tournament-list">{events.concat([{ title: "MIDNIGHT // LAST CHANCE", tag: "COMMUNITY", date: "JUL 11 · 21:00", teams: "12 / 16", prize: "$300", status: "4 SLOTS", tone: "purple" }]).map((event) => <article className="tournament-row" key={event.title}><div className={`row-art ${event.tone}`}><span>{event.tone === "gold" ? "✦" : "×"}</span></div><div className="row-main"><span className="event-tag">{event.tag}</span><h3>{event.title}</h3><p><CalendarDays size={13} /> {event.date} <Users size={13} /> {event.teams}</p></div><div className="row-prize"><small>PRIZE POOL</small><b>{event.prize}</b></div><button className="realm-btn small-btn" onClick={() => setModal(event.status === "FULL" ? "full" : "register")}>{event.status === "FULL" ? "VIEW EVENT" : "REGISTER"} <ArrowRight size={13} /></button></article>)}</div></section>; }
function Ranked() { return <section className="page-section"><div className="page-heading"><span className="eyebrow red">VANT REALM / COMPETITIVE</span><h1>CLIMB THE<br /><em>LADDER.</em></h1><p>Your rank is more than a number. It’s a receipt.</p></div><div className="rank-hero-card"><div className="rank-emblem">V</div><div><span className="eyebrow">CURRENT SEASON / 01</span><h2>NA CIRCUIT</h2><p>2,418 verified players · Updated every match</p></div><div className="rank-score"><b>1,842</b><span>RATING</span></div></div><div className="full-ladder">{leaderboard.concat([["06", "FlyQuest", "1,612", "↑ 3"], ["07", "100 Thieves", "1,590", "—"]]).map((row) => <div className="rank-row" key={row[0]}><span className="rank-num">{row[0]}</span><span className="rank-team"><span className="mini-shield" />{row[1]}</span><b>{row[2]}</b><span className="up">{row[3]}</span></div>)}</div></section>; }
function Players() { return <section className="page-section"><div className="page-heading"><span className="eyebrow red">VANT REALM / ROSTER</span><h1>FIND YOUR<br /><em>FIVE.</em></h1><p>Verified players. Real stats. No smurfs.</p></div><div className="player-grid">{["t3xture", "johnqt", "Zellsis", "valyn", "something", "jawgemo"].map((player, index) => <article className="player-card" key={player}><div className={`player-avatar avatar-${index % 3}`}><span>{player.slice(0, 1).toUpperCase()}</span></div><div><span className="eyebrow">RANKED #{index + 1}</span><h3>{player}</h3><p><Crosshair size={13} /> Duelist · NA</p></div><strong>{1842 - index * 43}</strong></article>)}</div></section>; }
function Modal({ type, close }: { type: string; close: () => void }) { const title = type === "search" ? "SEARCH THE REALM" : type === "login" ? "WELCOME BACK" : type === "how" ? "HOW THE CIRCUIT WORKS" : type === "match" ? "MATCH CENTER" : type === "full" ? "EVENT FULL" : "ENTER THE CIRCUIT"; return <div className="modal-layer" onClick={close}><div className="realm-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={close}><X size={18} /></button><span className="eyebrow red">VANT REALM</span><h2>{title}</h2>{type === "search" ? <div className="modal-input"><Search size={16} /><input autoFocus placeholder="Search players, teams, events..." /></div> : type === "full" ? <p>This bracket is locked. Join the waitlist and we’ll notify you if a slot opens.</p> : <p>Demo interaction — this is where the real VANT REALM flow will continue.</p>}<button className="realm-btn red-btn" onClick={close}>{type === "full" ? "JOIN WAITLIST" : "CONTINUE"} <ArrowRight size={14} /></button></div></div>; }
