-- Inbound forms, Discord outbox, and bot sync. Text/int ids for PGLite + Neon.

create table if not exists contact_leads (
  id text primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  source text not null default 'contact',
  discord_username text,
  payload text,
  created_at timestamptz not null default now()
);

create index if not exists contact_leads_created_at_idx on contact_leads (created_at desc);

create table if not exists vant_sync_events (
  id integer primary key generated by default as identity,
  event_type text not null,
  idempotency_key text not null unique,
  payload text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  lease_token text,
  lease_until timestamptz,
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists vant_sync_events_pending_idx
  on vant_sync_events (status, created_at);

create table if not exists player_discord_accounts (
  user_id text primary key,
  discord_id text not null unique,
  discord_username text,
  avatar_url text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
