/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as OndasRouteImport } from './routes/ondas'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as RankedRouteImport } from './routes/ranked'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyPurchaseRouteImport } from './routes/verify-purchase'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as JoinPlanIdRouteImport } from './routes/join.$planId'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersUsernameRouteImport } from './routes/players.$username'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsPrivateRouteImport } from './routes/tournaments.private'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDiscordEventsRouteImport } from './routes/api/discord/events'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiVantApplicationsRouteImport } from './routes/api/vant/applications'
import { Route as ApiVantEventsRouteImport } from './routes/api/vant/events'
import { Route as ApiVantEventsIdAckRouteImport } from './routes/api/vant/events.$id.ack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const OndasRoute = OndasRouteImport.update({
  id: '/ondas',
  path: '/ondas',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const RankedRoute = RankedRouteImport.update({
  id: '/ranked',
  path: '/ranked',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPurchaseRoute = VerifyPurchaseRouteImport.update({
  id: '/verify-purchase',
  path: '/verify-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const JoinPlanIdRoute = JoinPlanIdRouteImport.update({
  id: '/join/$planId',
  path: '/join/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LegalRoute,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const PlayersUsernameRoute = PlayersUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => PlayersRoute,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRoute,
} as any)
const TournamentsPrivateRoute = TournamentsPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => TournamentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordEventsRoute = ApiDiscordEventsRouteImport.update({
  id: '/api/discord/events',
  path: '/api/discord/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVantApplicationsRoute = ApiVantApplicationsRouteImport.update({
  id: '/api/vant/applications',
  path: '/api/vant/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVantEventsRoute = ApiVantEventsRouteImport.update({
  id: '/api/vant/events',
  path: '/api/vant/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVantEventsIdAckRoute = ApiVantEventsIdAckRouteImport.update({
  id: '/$id/ack',
  path: '/$id/ack',
  getParentRoute: () => ApiVantEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/globe': typeof GlobeRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/ondas': typeof OndasRoute
  '/ops': typeof OpsRoute
  '/players': typeof PlayersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/proyectos': typeof ProyectosRoute
  '/ranked': typeof RankedRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/verification': typeof VerificationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-purchase': typeof VerifyPurchaseRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/join/$planId': typeof JoinPlanIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/players/$username': typeof PlayersUsernameRoute
  '/tournaments/private': typeof TournamentsPrivateRoute
  '/legal/': typeof LegalIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/events': typeof ApiDiscordEventsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/vant/applications': typeof ApiVantApplicationsRoute
  '/api/vant/events': typeof ApiVantEventsRouteWithChildren
  '/api/vant/events/$id/ack': typeof ApiVantEventsIdAckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/ondas': typeof OndasRoute
  '/ops': typeof OpsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/proyectos': typeof ProyectosRoute
  '/ranked': typeof RankedRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/verification': typeof VerificationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-purchase': typeof VerifyPurchaseRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/join/$planId': typeof JoinPlanIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/players/$username': typeof PlayersUsernameRoute
  '/tournaments/private': typeof TournamentsPrivateRoute
  '/legal': typeof LegalIndexRoute
  '/players': typeof PlayersIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/events': typeof ApiDiscordEventsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/vant/applications': typeof ApiVantApplicationsRoute
  '/api/vant/events': typeof ApiVantEventsRouteWithChildren
  '/api/vant/events/$id/ack': typeof ApiVantEventsIdAckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founders': typeof FoundersRoute
  '/globe': typeof GlobeRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/ondas': typeof OndasRoute
  '/ops': typeof OpsRoute
  '/players': typeof PlayersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/proyectos': typeof ProyectosRoute
  '/ranked': typeof RankedRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/verification': typeof VerificationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-purchase': typeof VerifyPurchaseRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/join/$planId': typeof JoinPlanIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/players/$username': typeof PlayersUsernameRoute
  '/tournaments/private': typeof TournamentsPrivateRoute
  '/legal/': typeof LegalIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/discord/events': typeof ApiDiscordEventsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/vant/applications': typeof ApiVantApplicationsRoute
  '/api/vant/events': typeof ApiVantEventsRouteWithChildren
  '/api/vant/events/$id/ack': typeof ApiVantEventsIdAckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/account'
    | '/admin'
    | '/apply'
    | '/checkout'
    | '/contacto'
    | '/cookies'
    | '/dashboard'
    | '/error'
    | '/events'
    | '/forgot-password'
    | '/founders'
    | '/globe'
    | '/legal'
    | '/login'
    | '/my-tickets'
    | '/ondas'
    | '/ops'
    | '/players'
    | '/pricing'
    | '/profile'
    | '/proyectos'
    | '/ranked'
    | '/register'
    | '/reset-password'
    | '/roster'
    | '/settings'
    | '/success'
    | '/support'
    | '/tickets'
    | '/tournaments'
    | '/verification'
    | '/verify-email'
    | '/verify-purchase'
    | '/checkout/$productId'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/join/$planId'
    | '/legal/$slug'
    | '/players/$username'
    | '/tournaments/private'
    | '/legal/'
    | '/players/'
    | '/tournaments/'
    | '/api/auth/$'
    | '/api/discord/events'
    | '/api/stripe/webhook'
    | '/api/vant/applications'
    | '/api/vant/events'
    | '/api/vant/events/$id/ack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/account'
    | '/admin'
    | '/apply'
    | '/checkout'
    | '/contacto'
    | '/cookies'
    | '/dashboard'
    | '/error'
    | '/events'
    | '/forgot-password'
    | '/founders'
    | '/globe'
    | '/login'
    | '/my-tickets'
    | '/ondas'
    | '/ops'
    | '/pricing'
    | '/profile'
    | '/proyectos'
    | '/ranked'
    | '/register'
    | '/reset-password'
    | '/roster'
    | '/settings'
    | '/success'
    | '/support'
    | '/tickets'
    | '/verification'
    | '/verify-email'
    | '/verify-purchase'
    | '/checkout/$productId'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/join/$planId'
    | '/legal/$slug'
    | '/players/$username'
    | '/tournaments/private'
    | '/legal'
    | '/players'
    | '/tournaments'
    | '/api/auth/$'
    | '/api/discord/events'
    | '/api/stripe/webhook'
    | '/api/vant/applications'
    | '/api/vant/events'
    | '/api/vant/events/$id/ack'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/account'
    | '/admin'
    | '/apply'
    | '/checkout'
    | '/contacto'
    | '/cookies'
    | '/dashboard'
    | '/error'
    | '/events'
    | '/forgot-password'
    | '/founders'
    | '/globe'
    | '/legal'
    | '/login'
    | '/my-tickets'
    | '/ondas'
    | '/ops'
    | '/players'
    | '/pricing'
    | '/profile'
    | '/proyectos'
    | '/ranked'
    | '/register'
    | '/reset-password'
    | '/roster'
    | '/settings'
    | '/success'
    | '/support'
    | '/tickets'
    | '/tournaments'
    | '/verification'
    | '/verify-email'
    | '/verify-purchase'
    | '/checkout/$productId'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/join/$planId'
    | '/legal/$slug'
    | '/players/$username'
    | '/tournaments/private'
    | '/legal/'
    | '/players/'
    | '/tournaments/'
    | '/api/auth/$'
    | '/api/discord/events'
    | '/api/stripe/webhook'
    | '/api/vant/applications'
    | '/api/vant/events'
    | '/api/vant/events/$id/ack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  ErrorRoute: typeof ErrorRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FoundersRoute: typeof FoundersRoute
  GlobeRoute: typeof GlobeRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyTicketsRoute: typeof MyTicketsRoute
  OndasRoute: typeof OndasRoute
  OpsRoute: typeof OpsRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProyectosRoute: typeof ProyectosRoute
  RankedRoute: typeof RankedRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RosterRoute: typeof RosterRoute
  SettingsRoute: typeof SettingsRoute
  SuccessRoute: typeof SuccessRoute
  SupportRoute: typeof SupportRoute
  TicketsRoute: typeof TicketsRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  VerificationRoute: typeof VerificationRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyPurchaseRoute: typeof VerifyPurchaseRoute
  JoinPlanIdRoute: typeof JoinPlanIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDiscordEventsRoute: typeof ApiDiscordEventsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiVantApplicationsRoute: typeof ApiVantApplicationsRoute
  ApiVantEventsRoute: typeof ApiVantEventsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ondas': {
      id: '/ondas'
      path: '/ondas'
      fullPath: '/ondas'
      preLoaderRoute: typeof OndasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranked': {
      id: '/ranked'
      path: '/ranked'
      fullPath: '/ranked'
      preLoaderRoute: typeof RankedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-purchase': {
      id: '/verify-purchase'
      path: '/verify-purchase'
      fullPath: '/verify-purchase'
      preLoaderRoute: typeof VerifyPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/join/$planId': {
      id: '/join/$planId'
      path: '/join/$planId'
      fullPath: '/join/$planId'
      preLoaderRoute: typeof JoinPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof LegalRoute
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/players/$username': {
      id: '/players/$username'
      path: '/$username'
      fullPath: '/players/$username'
      preLoaderRoute: typeof PlayersUsernameRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/tournaments/private': {
      id: '/tournaments/private'
      path: '/private'
      fullPath: '/tournaments/private'
      preLoaderRoute: typeof TournamentsPrivateRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/events': {
      id: '/api/discord/events'
      path: '/api/discord/events'
      fullPath: '/api/discord/events'
      preLoaderRoute: typeof ApiDiscordEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vant/applications': {
      id: '/api/vant/applications'
      path: '/api/vant/applications'
      fullPath: '/api/vant/applications'
      preLoaderRoute: typeof ApiVantApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vant/events': {
      id: '/api/vant/events'
      path: '/api/vant/events'
      fullPath: '/api/vant/events'
      preLoaderRoute: typeof ApiVantEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vant/events/$id/ack': {
      id: '/api/vant/events/$id/ack'
      path: '/$id/ack'
      fullPath: '/api/vant/events/$id/ack'
      preLoaderRoute: typeof ApiVantEventsIdAckRouteImport
      parentRoute: typeof ApiVantEventsRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface LegalRouteChildren {
  LegalSlugRoute: typeof LegalSlugRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalSlugRoute: LegalSlugRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface PlayersRouteChildren {
  PlayersUsernameRoute: typeof PlayersUsernameRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersUsernameRoute: PlayersUsernameRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface TournamentsRouteChildren {
  TournamentsPrivateRoute: typeof TournamentsPrivateRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsPrivateRoute: TournamentsPrivateRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

interface ApiVantEventsRouteChildren {
  ApiVantEventsIdAckRoute: typeof ApiVantEventsIdAckRoute
}

const ApiVantEventsRouteChildren: ApiVantEventsRouteChildren = {
  ApiVantEventsIdAckRoute: ApiVantEventsIdAckRoute,
}

const ApiVantEventsRouteWithChildren = ApiVantEventsRoute._addFileChildren(
  ApiVantEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  ErrorRoute: ErrorRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FoundersRoute: FoundersRoute,
  GlobeRoute: GlobeRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  MyTicketsRoute: MyTicketsRoute,
  OndasRoute: OndasRoute,
  OpsRoute: OpsRoute,
  PlayersRoute: PlayersRouteWithChildren,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProyectosRoute: ProyectosRoute,
  RankedRoute: RankedRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RosterRoute: RosterRoute,
  SettingsRoute: SettingsRoute,
  SuccessRoute: SuccessRoute,
  SupportRoute: SupportRoute,
  TicketsRoute: TicketsRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  VerificationRoute: VerificationRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyPurchaseRoute: VerifyPurchaseRoute,
  JoinPlanIdRoute: JoinPlanIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDiscordEventsRoute: ApiDiscordEventsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiVantApplicationsRoute: ApiVantApplicationsRoute,
  ApiVantEventsRoute: ApiVantEventsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
